/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/gases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get standard diving gases */
        get: operations["get_gases_api_gases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cylinders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get standard cylinder sizes */
        get: operations["get_cylinders_api_cylinders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calculate a dive plan */
        post: operations["plan_dive_api_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DivePlanRequest */
        DivePlanRequest: {
            /** Depth */
            depth: number;
            /** Bottom Time */
            bottom_time: number;
            /** Bottom Gas */
            bottom_gas: string;
            /** Deco Gases */
            deco_gases: string[];
            /**
             * Gf Low
             * @default 50
             */
            gf_low: number;
            /**
             * Gf High
             * @default 80
             */
            gf_high: number;
            /**
             * Is Ccr
             * @default false
             */
            is_ccr: boolean;
            /**
             * Setpoint
             * @default 1.2
             */
            setpoint: number;
            /**
             * Deco Setpoint
             * @default 1.2
             */
            deco_setpoint: number;
            /**
             * Descent Rate
             * @default 20
             */
            descent_rate: number;
            /**
             * Ascent Rate
             * @default 10
             */
            ascent_rate: number;
            /**
             * Force 6M
             * @default true
             */
            force_6m: boolean;
            /**
             * Model
             * @default C
             */
            model: string;
        };
        /** DivePlanResponse */
        DivePlanResponse: {
            /** Schedule */
            schedule: components["schemas"]["ScheduleEntry"][];
            /** Profile */
            profile: components["schemas"]["ProfileEntry"][];
            gas_requirements: components["schemas"]["GasRequirements"];
            /** Cns Percent */
            cns_percent: number;
            /** Otus */
            otus: number;
            /** Tissue Loads */
            tissue_loads: components["schemas"]["TissueLoad"][];
            /** Surface Gf */
            surface_gf: number;
            /** Warnings */
            warnings: string[];
        };
        /** GasMix */
        GasMix: {
            /** Name */
            name: string;
            /** Fo2 */
            fO2: number;
            /** Fhe */
            fHe: number;
            /** Type */
            type: string;
        };
        /** GasRequirements */
        GasRequirements: {
            /** Bailout */
            bailout: {
                [key: string]: number;
            };
            /** Onboard */
            onboard: {
                [key: string]: number;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ProfileEntry */
        ProfileEntry: {
            /** Time */
            time: number;
            /** Depth */
            depth: number;
            /** Gas */
            gas: string;
        };
        /** ScheduleEntry */
        ScheduleEntry: {
            /** Depth */
            depth: number;
            /** Time */
            time: number;
            /** Run Time */
            run_time: number;
            /** Gas */
            gas: string;
            /** Cns */
            cns: number;
            /** Otu */
            otu: number;
        };
        /** TissueLoad */
        TissueLoad: {
            /** Compartment */
            compartment: number;
            /** N2 Pressure */
            n2_pressure: number;
            /** He Pressure */
            he_pressure: number;
            /** Total Pressure */
            total_pressure: number;
            /** Load Percent */
            load_percent: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_gases_api_gases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of available gases */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GasMix"][];
                };
            };
        };
    };
    get_cylinders_api_cylinders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of available cylinders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    plan_dive_api_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DivePlanRequest"];
            };
        };
        responses: {
            /** @description Detailed dive schedule and gas requirements */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DivePlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
